dataset: adv_squad
model: varun-v-rao/roberta-large-squad
tokenizer: varun-v-rao/roberta-large-squad
exp_params:
  path: "squad_adversarial"
  setup: AddOneSent
  split: validation
  output: "${GENERALIZATION_HOME}/nlp_generalization/results/adv_squad-squad-test/rl-addonesent.jsonl"
