dataset: varun-v-rao/adversarial_hotpotqa
tokenizer: bert-base-cased
model:
  model_type: adapter
  base_model: bert-base-cased
  model_name: varun-v-rao/bert-base-cased-bn-adapter-895K-squad-model2
  